### ISSUE TITLE
Removing vendor from repository

### ISSUE THREAD

**Issue by dhiemaz** [Eun/go-hit#2]
There is vendor folder from the repository, you should remove or ignored it and just push the code only without vendor dependencies

**Comment by Eun** [comment]
Omitting the vendor folder means failing builds if the author decides to delete their repository. This is a too high risk.

**Comment by dhiemaz** [comment]
as I can see you use go module as your dependency management, so when user use `go get` it will also get the dependencies of your project. So I think it will be lighter to just push your code only.

**Comment by Eun** [comment]
I don't think you understood my previous comment, let me give you an example:
what happens if `github.com/davecgh/go-spew` disappears?
`go get -u github.com/Eun/go-hit` will fail until I replace the dependency.

**Comment by dhiemaz** [comment]
Ah yes, go the point @Eun, but I don't think you should put `golang.org/x/sys` also into vendor folder. Because I don't think golang.org library will disappear.

**Comment by Eun** [comment]
`vendor` is managed by `go mod` so removing folders from there is not a good idea.
